[package]
name = "pg-bridge-tests"
version = "0.1.0"
authors = ["Eric B. Ridge <eebbrr@gmail.com>"]
edition = "2018"

[dependencies]
pg-bridge = { path = "../pg-bridge" }
elog-guard = { path = "../pg-bridge/elog-guard" }
elog-wrapper = { path = "../pg-bridge/elog-wrapper" }