language: java
sudo: required
before_script:
  - sudo apt-get install postgresql-9.3
  - sudo apt-get install postgresql-client-9.3
  - sudo apt-get install postgresql-server-dev-9.3
before_install:
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start 9.3
