language: ruby

env:
  matrix:
    - ES=5.6.9 PG=10
    - ES=6.2.4 PG=10
    - ES=5.6.9 PG=11
    - ES=6.2.4 PG=11

sudo: required
dist: xenial

notifications:
  slack: zombodb:M95qGlYZ9x9ufL6L3oRxyGBm

before_install:
  - sudo apt-get -y remove postgresql* elasticsearch*
  - sudo apt-get -y purge postgresql* elasticsearch*
  - sudo apt-get update -y -qq --fix-missing
  - sudo apt-get install -y wget
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt xenial-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo apt-get update -y --fix-missing
  - sudo apt-get install -y libcurl4-openssl-dev
  - sudo apt-get install -y gcc make build-essential libz-dev zlib1g-dev strace
  - sudo apt-get install -y postgresql-server-dev-${PG}
  - sudo apt-get install -y postgresql-${PG}
  - sudo apt-get update -y -qq --fix-missing
  - sudo apt-get install -y postgresql-${PG}-postgis-2.5
  - sudo apt-get install -y postgresql-${PG}-postgis-2.5-scripts
  - chmod -R a+rwx ~/
  - wget --no-check-certificate https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES}.tar.gz
  - tar xzf ./elasticsearch-${ES}.tar.gz

script:
  - elasticsearch-${ES}/bin/elasticsearch -d
  - sudo /etc/init.d/postgresql stop ${PG}
  - sudo src/test/travis/hack-configs.sh ${PG}
  - sudo /etc/init.d/postgresql start ${PG}
  - sudo su - postgres -c "createuser --superuser travis"
  - make && sudo make install
  - sleep 10
  - curl localhost:9200/
  - make installcheck-setup installcheck

after_failure:
  - sudo cat regression.diffs
  - sudo cat /var/log/postgresql/*.log
  - sudo cat elasticsearch-${ES}/logs/*.log | grep -v "deprecated"
  - df -h
  - free
