language: java
sudo: required
before_install:
  - sudo /etc/init.d/postgresql stop
  - sudo apt-get remove postgresql-9.4
  - sudo apt-get update -qq
  - sudo apt-get install -y postgresql-server-dev-9.3
  - sudo /etc/init.d/postgresql start 9.3
