language: ruby

env:
  matrix:
#    - ES=5.6.9 PG=10
#    - ES=6.2.4 PG=10
    - ES=5.6.9 PG=11
#    - ES=6.2.4 PG=11

sudo: required
dist: xenial

notifications:
  slack: zombodb:M95qGlYZ9x9ufL6L3oRxyGBm

before_install:
  - sudo apt-get update -y -qq
  - sudo apt-get install -y wget
  - sudo apt-get purge postgresql-9.4
  - sudo apt-get purge postgresql-9.5
  - sudo apt-get purge postgresql-9.6
  - sudo apt-get purge postgresql-10
  - sudo rm -rf /var/lib/postgresql/* /etc/postgresql/*
  - sudo rm -rf /usr/share/postgresql/*
  - sudo apt-get autoremove -y

  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt xenial-pgdg main" >> /etc/apt/sources.list'
  - wget --quiet -O - http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc | sudo apt-key add -
  - sudo apt update -y -qq
  - sudo apt-get install -y postgresql-${PG} postgresql-server-dev-${PG}
  - sudo apt update -y -qq
  - sudo apt install -y postgresql-${PG}-postgis-2.5
  - chmod -R a+rwx ~/
  - wget --no-check-certificate https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES}.tar.gz
  - tar xzf ./elasticsearch-${ES}.tar.gz

script:
  - ls -la /usr/share/postgresql/
  - find /usr/share/postgresql/ -type f -name "postgis.control"
  - find / -type f -name "postgis.control"

#  - elasticsearch-${ES}/bin/elasticsearch -d
#  - sudo /etc/init.d/postgresql stop ${PG}
#  - sudo src/test/travis/hack-configs.sh ${PG}
#  - sudo /etc/init.d/postgresql start ${PG}
#  - sudo su - postgres -c "createuser --superuser travis"
#  - make && sudo make install
#  - sleep 10
#  - curl localhost:9200/
#  - make installcheck-setup installcheck

#after_failure:
#  - sudo cat regression.diffs
#  - sudo cat /var/log/postgresql/*.log
#  - sudo cat elasticsearch-5.6.4/logs/*.log | grep -v "deprecated"
#  - df -h
#  - free
