[package]
name = "zombodb"
description = "Making Postgres and Elasticsearch work together like it's 2020"
version = "3000.0.0-alpha2"
edition = "2018"
build = "build.rs"
readme = "README.md"
license = "LICENSE.md"

[lib]
crate-type = [ "cdylib" ]

[features]
default = [ "pg12" ]
pg10 = [ "pgx/pg10", "pgx-tests/pg10" ]
pg11 = [ "pgx/pg11", "pgx-tests/pg11" ]
pg12 = [ "pgx/pg12", "pgx-tests/pg12" ]
pg13 = [ "pgx/pg13", "pgx-tests/pg13" ]
pg_test = [ ]

[dependencies]
chrono = "0.4.19"
crossbeam-channel = "0.5.0"
indexmap = "1.6.0"
lalrpop-util = "0.19.1"
lazy_static = "1.4.0"
levenshtein = "1.0.4"
memoffset = "0.6.1"
num_cpus = "1.13.0"
pathfinding = "2.0.4"
pgx = "0.1.6"
pgx-macros = "0.1.6"
rayon = "1.5.0"
regex = "1.4.2"
reqwest = "0.9.24"
serde = { version = "1.0.117", features = [ "derive" ] }
serde_json = { version = "1.0.59", features = [ "preserve_order" ] }
serde_cbor = "0.11.1"
sqlformat = "0.1.5"
url = "2.2.0"

[build-dependencies]
lalrpop = { version = "0.19.1", features = [ "lexer" ] }

[dev-dependencies]
pgx-tests = "0.1.6"
libc = "0.2.80"

[profile.dev]
panic = "unwind"
debug = true
opt-level = 0

[profile.release]
panic = "unwind"
opt-level = 3
lto = "fat"
codegen-units = 1

