[package]
name = "zombodb"
version = "5.0.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[features]
default = ["pg11"]
pg10 = ["pgx/pg10"]
pg11 = ["pgx/pg11"]
pg12 = ["pgx/pg12"]
pg_test = []

[dependencies]
pgx = { path = "../pgx/pgx/", default-features = false }
pgx-macros = { path = "../pgx/pgx-macros" }
lazy_static = "1.4.0"
libc = "0.2.66"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.46"
serde_cbor = "0.11.1"
url = "2.1.1"
crossbeam = "0.7.3"
num_cpus = "1.12.0"
memoffset = "0.5.3"
rand = "0.7.3"
reqwest = "0.9.24"
time = "0.2.7"

[dev-dependencies]
pgx-tests = { path = "../pgx/pgx-tests" }

[profile.dev]
panic = "unwind"
debug = true
opt-level = 0

[profile.release]
panic = "unwind"
opt-level = 3
lto = "fat"
codegen-units = 1
