[package]
name = "zombodb"
version = "5.0.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[features]
default = ["pgx/pg11"]
pg_test = []

[dependencies]
pgx = { path = "../pgx/pgx/", default-features = false }
pgx-macros = { path = "../pgx/pgx-macros" }
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.44"
serde_cbor = "0.11.1"
url = "2.1.1"
crossbeam = "0.7.3"
num_cpus = "1.12.0"
#ureq = { version = "0.11.3", features = ["json" ] }
reqwest = "0.9.24"

[dev-dependencies]
pgx-tests = { path = "../pgx/pgx-tests" }

[profile.dev]
panic = "unwind"
debug = true

[profile.release]
panic = "unwind"
opt-level = 3
lto = true
codegen-units = 1
