[package]
name = "pg-bridge"
version = "0.1.0"
authors = ["Eric B. Ridge <eebbrr@gmail.com>"]
edition = "2018"

[dependencies]
pg-guard = { path = "pg-guard/" }
elog-wrapper = { path = "elog-wrapper" }
